<?php

namespace GestionFraisBundle\Entity;

/**
 * EtatFicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatFicheFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
