<?php

namespace GestionFraisBundle\Entity;

/**
 * EtatLigneFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatLigneFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
