<?php

namespace GestionFraisBundle\Entity;

/**
 * FraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
