<?php

namespace GestionFraisBundle\Entity;

/**
 * LigneFraisHorsForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisHorsForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
